### ISSUE TITLE
应用软件系统开发大赛

### ISSUE THREAD

**Issue by mouxiaohui** [GatsbyH/sdcet-RuoYi-Mes-BigScreen#1]
是应用软件系统开发大赛吗？其他模块可以分享一下吗

**Comment by GatsbyH** [comment]
是的，几套样题合在一起的。其他模块差不多的吧？都是些crud操作，顶多有个多表联查。你想要哪个模块呢？

**Comment by mouxiaohui** [comment]
> 

就是模块1的任务，用例图、类图、时序图、E-R图之类的，我不太了解这些
